#!/usr/bin/bash

cmd="nc bach.nat.rhwyd.co.uk 30001"

case $1 in
    tv)
	echo "Main.Source=Coax1" | $cmd
	;;
    pi)
	echo "Main.Source=Opt1" | $cmd
	;;
    phono)
	echo "Main.Source=Phono" | $cmd
	;;
    cd)
	echo "Main.Source=TV" | $cmd
	;;
    radio)
	echo "Main.Source=Opt2" | $cmd
	;;
    off)
	echo "Main.Power=Off" | $cmd
	;;
    on)
	echo "Main.Power=On" | $cmd
	;;
esac

